remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme 
title: Adamantium Template Website bbb
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
