remote-theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme
title: Adamantium Template Website arr
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
