remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
baseurl: ""
title: Adamantium Template Website ddd
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
