remote-theme:  minimal-mistakes-jekyll
title: Adamantium Template Website
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
