remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
# SITE CONFIGURATION
baseurl: ""
url: "https://sw-e.github.io"
title: Adamantium Template Website ddd
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
